# How links connect together
kinematics:
  joint0:
    x: 0
    y: 0
    z: 0.0815
    roll: 0
    pitch: 0
    yaw: 0
  joint1:
    x: 0
    y: -0.1355
    z: 0.2685
    roll: 1.570796327
    pitch: -1.570796327
    yaw: 0
  joint2:
    x: 0.650
    y: 0
    z: -0.0185
    roll: 0
    pitch: 0
    yaw: 1.570796327
  joint3:
    x: 0
    y: -0.187
    z: -0.1065
    roll: -1.570796327
    pitch: 0
    yaw: 3.14159265
  joint4:
    x: 0
    y: -0.129
    z: 0.363
    roll: -1.570796327
    pitch: 0
    yaw: 3.14159265
  joint5:
    x: 0
    y: -0.074
    z: 0.0795
    roll: -1.570796327
    pitch: 0
    yaw: 3.14159265
  tcp:
    x: 0.0
    y: 0.0
    z: 0.085
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
