inertia_parameters:
  link0_mass: 12.0
  link1_mass: 30.0
  link2_mass: 20.0
  link3_mass: 9.0
  link4_mass: 8.0
  link5_mass: 8.0
  link6_mass: 1.0
  
  link0:
    ixx: 0.08385
    iyy: 0.08011
    izz: 0.1454
    iyz: 7.177e-06
    ixz: 0.0007205
    ixy: 0.0006467

  link1:
    ixx: 0.6829
    iyy: 0.5527
    izz: 0.5809
    iyz: 0.008554
    ixz: 7.98813e-05
    ixy: -1.5608e-06

  link2:
    ixx: 0.2539
    iyy: 0.1145
    izz: 0.2519
    iyz: -0.02939
    ixz: 8.31826e-05
    ixy: -0.0002374

  link3:
    ixx: 0.77317
    iyy: 0.02155
    izz: 0.7295
    iyz: -0.02049
    ixz: 4.0223e-05
    ixy: -0.0008483

  link4:
    ixx: 0.00529
    iyy: 0.003253
    izz: 0.005006
    iyz: 0.0003494
    ixz: 3.834e-07
    ixy: -9.029e-07

  link5:
    ixx: 0.00529
    iyy: 0.003253
    izz: 0.005006
    iyz: -0.0003494
    ixz: 3.834e-07
    ixy: 9.029e-07

  link6:
    ixx: 0.0003768
    iyy: 0.0003701
    izz: 0.0006321
    iyz: -4.0733e-06
    ixz: 4.611e-07
    ixy: -2.45e-08

  center_of_mass:
    link0:
      x: 0.001827
      y: 4.1e-05
      z: 0.034445
    link1:
      x: 7.0e-06
      y: 0.02402
      z: 0.115969
    link2:
      x: 0.000847
      y: 0.395788
      z: -0.112624
    link3:
      x: -2.9e-05
      y: 0.388213
      z: 0.076464
    link4:
      x: -6.0e-06
      y: 0.00463
      z: -0.066051
    link5:
      x: 6.0e-06
      y: 0.00463
      z: 0.066051
    link6:
      x: -1.3e-05
      y: -0.00024
      z: 0.021432
