mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30s/visual/Nuri30s_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30s/collision/Nuri30s_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30s/visual/Nuri30s_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30s/collision/Nuri30s_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30s/visual/Nuri30s_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30s/collision/Nuri30s_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30s/visual/Nuri30s_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30s/collision/Nuri30s_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30s/visual/Nuri30s_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30s/collision/Nuri30s_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30s/visual/Nuri30s_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30s/collision/Nuri30s_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30s/visual/Nuri30s_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30s/collision/Nuri30s_6.stl
